name: SkyLogic Technology
favicon: null
layout_spectrum: 1
typography_spectrum: 0.67573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#72aecb'
    - '#1374a5'
    - '#5a5653'
    - '#1c1b1a'
  brandStrength: 0
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 1
purpose: []
