name: SkyLogic Technology
favicon: null
layout_spectrum: 0.6849148746114224
typography_spectrum: 0.9713017682079226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6952868942171335
  lightness: 0.20136155234649777
  saturation: 0.6215901109389961
  rhythmicContrast: 0.17942377552390099
purpose: []
